### PR TITLE
Add Department of Physics McGill University, QC, Canada to exclude list

### PR DESCRIPTION
**Pull request by benjojo**
Since they sent me an abuse email asking not to be scanned again,
I figure that it's nice if it's added here so that others don't
bother them

### CODE REVIEW

**Comment by francisuk1989** [comment]
if you look up there ASN, (AS15318) they have alot more IP Ranges

132.206.0.0/16
132.216.0.0/16
142.157.0.0/16
142.157.0.0/17
142.157.128.0/18
142.157.192.0/18
192.197.121.0/24
198.168.128.0/18
199.202.80.0/22
199.202.84.0/23
199.202.98.0/23

Updated 22 Nov 2017 17:03 PST via Hurricane Electric

**Comment by benjojo** [comment]
Ah, I was only adding the ones I got an abuse email from. Figures that the rest of the University would be ok with it

**Comment by DamieFC** [comment]
Almost 3 years later... Why hasn't it been merged? It's reasonable.

**Comment by robertdavidgraham** [comment]
merged

**Pull request closed without merging**
